pipeline {
    agent any
    stages {
        stage('Checkout') {
            steps {
                checkout([
                    $class: 'GitSCM',
                    branches: [[name: '*/builds']],
                    extensions: [[$class: 'PathRestriction', excludedRegions: '', includedRegions: 'image-service/.*']],
                    userRemoteConfigs: [[url: 'https://github.com/unan25/TodayTrend.git']]
                ])
            }
        }
        stage('Gradle Build') {
            steps {
                dir('image-service') {
                    sh 'chmod +x gradlew'
                    sh './gradlew clean build -x test'
                }
            }
        }
        stage('Build and push Docker image') {
            steps {
                script {
                    dir('image-service') {
                        docker.withRegistry('https://registry.hub.docker.com', 'dockerhub-credentials') {
                            def app = docker.build("unan25/tt_image", "-f Dockerfile .")
                            app.push("latest")
                        }
                    }
                }
            }
        }

        stage('Clean Up') {
            steps {
                script {
                    sh 'sudo docker ps -q --filter "ancestor=unan25/tt_image" | xargs docker stop || true'
                    sh 'sudo docker ps -a -q --filter "ancestor=unan25/tt_image" | xargs docker rm || true'
                    sh 'sudo docker rmi unan25/tt_image:latest || true'
                }
            }
        }

        stage('Deploy to EC2') {
            steps {
                dir('image-service') {
                    sh """
                        ssh -o StrictHostKeyChecking=no ubuntu@ec2-3-38-93-126.ap-northeast-2.compute.amazonaws.com '
                            sudo docker stop \$(sudo docker ps -q) || true
                            sudo docker rm \$(sudo docker ps -a -q) || true
                            sudo docker rmi \$(sudo docker images -q) || true
                            sudo docker pull unan25/tt_image:latest
                            sudo docker run -d -p 12000:12000 unan25/tt_image:latest
                        '
                    """
                }
            }
        }
    }
}