pipeline {
    agent any
    stages {
        stage('Checkout') {
            steps {
                checkout([
                    $class: 'GitSCM',
                    branches: [[name: '*/builds']],
                    extensions: [[$class: 'PathRestriction', excludedRegions: '', includedRegions: 'post-service/.*']],
                    userRemoteConfigs: [[url: 'https://github.com/unan25/TodayTrend.git']]
                ])
            }
        }
        stage('Gradle Build') {
            steps {
                dir('post-service') {
                    sh 'chmod +x gradlew'
                    sh './gradlew clean build -x test'
                }
            }
        }
        stage('Build and push Docker image') {
            steps {
                script {
                    dir('post-service') {
                        docker.withRegistry('https://registry.hub.docker.com', 'dockerhub-credentials') {
                            def app = docker.build("unan25/tt_post", "-f Dockerfile .")
                            app.push("latest")
                        }
                    }
                }
            }
        }
        stage('Deploy to EC2') {
            steps {
                dir('post-service') {
                    sh """
                        ssh -o StrictHostKeyChecking=no ubuntu@ec2-13-125-79-9.ap-northeast-2.compute.amazonaws.com '
                            sudo docker stop \$(sudo docker ps -q) || true
                            sudo docker rm \$(sudo docker ps -a -q) || true
                            sudo docker rmi \$(sudo docker images -q) || true
                            sudo docker pull unan25/tt_post:latest
                            sudo docker run -d -p 11000:11000 unan25/tt_post:latest
                        '
                    """
                }
            }
        }
    }
}