pipeline {
    agent any
    stages {
        stage('Checkout') {
            steps {
                checkout([
                    $class: 'GitSCM',
                    branches: [[name: '*/builds']],
                    extensions: [[$class: 'PathRestriction', excludedRegions: '', includedRegions: 'apigateway-server/.*']],
                    userRemoteConfigs: [[url: 'https://github.com/unan25/TodayTrend.git']]
                ])
            }
        }
        stage('Gradle Build') {
            steps {
                dir('apigateway-server') {
                    sh 'chmod +x gradlew'
                    sh './gradlew clean build -x test'
                }
            }
        }
        stage('Build and push Docker image') {
            steps {
                script {
                    dir('apigateway-server') {
                        docker.withRegistry('https://registry.hub.docker.com', 'dockerhub-credentials') {
                            def app = docker.build("unan25/tt_gateway", "-f Dockerfile .")
                            app.push("latest")
                        }
                    }
                }
            }
        }
        stage('Deploy to EC2') {
            steps {
                dir('apigateway-server') {
                    sh '''
                        ssh -o StrictHostKeyChecking=no ubuntu@13.209.76.6 "
                            sudo docker stop \$(docker ps -q) || true
                            sudo docker rm \$(docker ps -a -q) || true
                            sudo docker rmi \$(docker images -q) || true
                            sudo docker pull unan25/tt_gateway:latest
                            sudo docker run -d -p 8000:8000 unan25/tt_gateway:latest
                        "
                    '''
                }
            }
        }
    }
}
