pipeline {
    agent any
    stages {
        stage('Checkout') {
            steps {
                checkout([
                    $class: 'GitSCM',
                    branches: [[name: '*/builds']],
                    extensions: [[$class: 'PathRestriction', excludedRegions: '', includedRegions: 'user-service/.*']],
                    userRemoteConfigs: [[url: 'https://github.com/unan25/TodayTrend.git']]
                ])
            }
        }
        
        stage('Gradle Build') {
            steps {
                dir('user-service') {
                    sh 'chmod +x gradlew'
                    sh './gradlew clean build -x test'
                }
            }
        }

        stage('Build and push Docker image') {
            steps {
                script {
                    dir('user-service') {
                        docker.withRegistry('https://registry.hub.docker.com', 'dockerhub-credentials') {
                            def app = docker.build("unan25/tt_user", "-f Dockerfile .")
                            app.push("latest")
                        }
                    }
                }
            }
        }

        stage('Clean Up') {
            steps {
                script {
                    sh 'sudo docker ps -q --filter "ancestor=unan25/tt_user" | xargs docker stop || true'
                    sh 'sudo docker ps -a -q --filter "ancestor=unan25/tt_user" | xargs docker rm || true'
                    sh 'sudo docker rmi unan25/tt_user:latest || true'
                }
            }
        }

        stage('Deploy to EC2') {
            steps {
                dir('user-service') {
                    sh """
                        ssh -o StrictHostKeyChecking=no ubuntu@ec2-3-38-107-1.ap-northeast-2.compute.amazonaws.com '
                            # Your deployment script
                        '
                    """
                }
            }
        }
    }
}
