pipeline {
    agent any
    stages {
        stage('Checkout') {
            steps {
                checkout([
                    $class: 'GitSCM',
                    branches: [[name: '*/builds']],
                    extensions: [[$class: 'PathRestriction', excludedRegions: '', includedRegions: 'user-service/.*']],
                    userRemoteConfigs: [[url: 'https://github.com/unan25/TodayTrend.git']]
                ])
            }
        }
        stage('Gradle Build') {
            steps {
                dir('user-service') {
                    sh 'chmod +x gradlew'
                    sh './gradlew clean build -x test'
                }
            }
        }
        stage('Build and push Docker image') {
            steps {
                script {
                    dir('user-service') {
                        docker.withRegistry('https://registry.hub.docker.com', 'dockerhub-credentials') {
                            def app = docker.build("unan25/tt_user", "-f Dockerfile .")
                            app.push("latest")
                        }
                    }
                }
            }
        }

        stage('Clean Up') {
            steps {
                script {
                    // 현재 사용 중인 컨테이너를 찾아 종료
                    sh 'sudo docker ps -q --filter "ancestor=unan25/tt_user" | xargs docker stop || true'

                     // 모든 컨테이너를 삭제
                    sh 'sudo docker ps -a -q --filter "ancestor=unan25/tt_user" | xargs docker rm || true'

                    // 이미지를 삭제
                    sh 'sudo docker rmi unan25/tt_user:latest || true'
                }
            }
        }

        stage('Deploy to EC2') {
            steps {
                dir('user-service') {
                    sh """
                        ssh -o StrictHostKeyChecking=no ubuntu@ec2-3-38-107-1.ap-northeast-2.compute.amazonaws.com '
                            sudo docker stop \$(sudo docker ps -q) || true
                            sudo docker rm \$(sudo docker ps -a -q) || true
                            sudo docker rmi \$(sudo docker images -q) || true
                            sudo docker pull unan25/tt_user:latest
                            sudo docker run -d -p 10000:10000 unan25/tt_user:latest
                        '
                    """
                }
            }
        }